# Generated by Django 6.0.6 on 2026-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_manifestoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='page',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
