# Generated by Django 6.0.6 on 2026-06-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_about_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.RemoveField(
            model_name='manifesto',
            name='content',
        ),
        migrations.AddField(
            model_name='manifesto',
            name='description',
            field=models.TextField(default='Coming soon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifesto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='manifesto_videos/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
