# Generated by Django 6.0.6 on 2026-06-24 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_contactmessage_delete_about_delete_homecontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manifesto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manifesto',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manifesto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='manifesto/'),
        ),
    ]
