# Generated by Django 6.0.6 on 2026-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_gallery_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
