# Generated by Django 6.0.6 on 2026-06-27 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_pagecontent_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagecontent',
            name='background_image',
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='name',
            field=models.CharField(choices=[('home', 'Home'), ('about', 'About')], max_length=50, unique=True),
        ),
    ]
