# Generated by Django 6.0.6 on 2026-06-27 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_remove_pagecontent_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
