# Generated by Django 6.0.6 on 2026-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_pagecontent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
